version: '3.8'

networks:
  dclearn:
    driver: bridge

services:
  nginx:
    image: nginx:stable-perl
    hostname: nginxs
    container_name: nginx_server
    volumes:                  
      - ./html:/usr/share/nginx/html:ro  # Mount the directory containing index.html
    ports:
      - "10080:80"  # Expose Nginx on port 8080
    networks:
      - dclearn

  proxy_manager:
    image: jc21/nginx-proxy-manager:latest
    hostname: nginxpm
    container_name: nginx_proxy_manager
    ports:
      - "80:80"
      - "81:81"  # Admin port for Nginx Proxy Manager
      - "443:443"
    environment:
      DB_SQLITE_FILE: "/data/database.sqlite"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - dclearn
